# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog
email: #taohu620@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  concise research summary drafts(always updating when necessary) and random thoughts
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

collections:
    drafts:
        output: true
        permalink: /:collection/:name/
    notes:
        output: true
        permalink: /:collection/:name/

defaults:
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: draft


#twitter_username: dongzhuoyao
#github_username:  dongzhuoyao
#linkedin_username: dongzhuoyao

# Build settings
markdown: kramdown